### PR TITLE
python3 upgrade

### PR DESCRIPTION
**Pull request by johndpope**
hi 
- the branch actually fails with 

(tensorflow) ➜  Synthetic Data git:(master) ✗ python Main.py
```
20
Traceback (most recent call last):
  File "Main.py", line 324, in <module>
    main()
  File "Main.py", line 170, in main
    target_params = cPickle.load(file.decode('utf-8'))
AttributeError: '_io.BufferedReader' object has no attribute 'decode'
```
(tensorflow) ➜  Synthetic Data git:(master) ✗ cd ..

I'm not sure if you can work it work it out. 
file = open('save/target_params.pkl', 'rb')
+    target_params = cPickle.load(file.decode('utf-8'))

pickle fails to load pkl file.

### CODE REVIEW

**Comment by Chillee** [comment]
That's a pretty simple problem.

You just need to do `    target_params = pickle.load(open('save/target_params.pkl', 'rb'), encoding="latin1")`.

The bigger problem is that after fixing those issues, I'm getting
```
20
(64, ?, 1720)
(?, ?, 1720)
Traceback (most recent call last):
  File "Main.py", line 320, in <module>
    main()
  File "Main.py", line 173, in main
    learning_rate=LEARNING_RATE)
  File "/home/chilli/tmp/LeakGAN/Synthetic Data/LeakGANModel.py", line 250, in __init__
    self.pretrain_manager_updates = pretrain_manager_opt.apply_gradients(zip(self.pretrain_manager_grad, self.manager_params),global_step=global_step_pre)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 472, in apply_gradients
    ([str(v) for _, _, v in converted_grads_and_vars],))
ValueError: No gradients provided for any variable: ['<tensorflow.python.training.optimizer._RefVariableProcessor object at 0x7efff3be7320>', 
```

Any idea?

**Comment by Chillee** [comment]
Actually, I fixed the necessary issues I think.

@CR-Gjx Do you think it's best for me to upload it to a separate repo or would you take some kind of PR?

**Comment by Chillee** [comment]
I've pushed my fork here. https://github.com/Chillee/LeakGAN

**Comment by CR-Gjx** [comment]
Thanks! In the Synthetic Data folder, it takes about 12 hours for 20-length texts and 24 hours for 40-length texts. In the Image Coco folder, it will take at least 12 hours to obtain a good effect. 
In addition, if you want to use this source code in other real datasets, you can use the source code in the Image Coco folder.
Thanks again for your contribution.

**Comment by Chillee** [comment]
@CR-Gjx Wait, if you were trying to merge a python3 fork that worked, you merged the wrong one. I'm not the original OP of this pull request. I pushed my fork here: https://github.com/Chillee/LeakGAN

The current version you just merged in crashes in python 3, and I believe it also crashes for python 2.

**Comment by johndpope** [comment]
sorry @CR-Gjx - I created a revert PR
@Chillee - please open up a new PR. 
 thanks in advance

**Pull request merged**
